### ISSUE TITLE
Command "post_fansub" not posting ending parenthesis for last link.

### ISSUE THREAD

**Issue by OrangeChannel** [Infiziert90/Tsuzuru-Bot#7]
Doesn't seem to be a character limit.

![image](https://user-images.githubusercontent.com/10972040/53528112-a64c7c00-3ab6-11e9-9b85-5586bb89988a.png)
![image](https://user-images.githubusercontent.com/10972040/53528119-aa789980-3ab6-11e9-8bdf-2ca6bc42b8ae.png)

**Comment by Infiziert90** [comment]
fixed
